### ISSUE TITLE
otpauth require apple-otpauth on import

### ISSUE THREAD

**Issue by idarek** [IngmarStein/1pif-to-csv#2]
Great script!
not able to use `go get` but downloaded and run `go run main.go...` instead and all fine.

Just a heads up, that otpauth://totp need to be manually changed to apple-otpauth://totp if you want to import it correctly in MacOS Monterey. 

Not a big issue, as Excel Replace can deal with that, but if you want to amend will make very good tool!

**Comment by IngmarStein** [comment]
Ah, thanks for finding the missing link! I'll change that right away.

**Comment by IngmarStein** [comment]
Updated in https://github.com/IngmarStein/1pif-to-csv/commit/23e5f6127bbe900d651706af28844e212d8f263f

**Comment by IngmarStein** [comment]
I've just tried the batch import again (which takes an astounding amount of time for ~700 passwords) and it looks like the OTPAuth links for existing entries are not amended. It works when I open the apple-otpauth links in Safari. Did it work for you without manual steps?

**Comment by idarek** [comment]
I open my csv file generated by your script, changed otpauth to apple-otpauth and yes, it import in Monterey correctly and showing codes that match with what I got in other Authenticator app.

**Comment by IngmarStein** [comment]
Ok, I just verified with a smaller subset and Monterey indeed does update existing entries with TOTP data. Looks like something may be broken when processing a large number (the `secd` process goes crazy). Thanks for your feedback!

**Comment by idarek** [comment]
I imported 890 :) with like 20-30OTP
